# Generated by Django 4.0.8 on 2022-10-10 19:27

from django.db import migrations, models
import djongo.models.fields
import translator.models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('english', djongo.models.fields.EmbeddedField(model_container=translator.models.FarmerDetails)),
                ('hindi', djongo.models.fields.EmbeddedField(model_container=translator.models.FarmerDetails)),
                ('marathi', djongo.models.fields.EmbeddedField(model_container=translator.models.FarmerDetails)),
                ('telugu', djongo.models.fields.EmbeddedField(model_container=translator.models.FarmerDetails)),
                ('punjabi', djongo.models.fields.EmbeddedField(model_container=translator.models.FarmerDetails)),
                ('file_id', models.CharField(max_length=24)),
            ],
        ),
    ]
